apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: organistation-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/OrganiStation-org/organistation-chart.git
    targetRevision: develop
    path: .
    helm:
      valueFiles:
        - dev-values.yaml
      parameters:
        - name: global.namespace
          value: dev-ns
        - name: global.keyvaultName
          value: ${KEYVAULT_NAME}
        - name: global.azureTenantId
          value: ${AZURE_TENANT_ID}
        - name: global.userAssignedIdentityID
          value: ${AKS_WORKLOAD_IDENTITY_ID}
        - name: auth.image.name
          value: ${ACR_LOGIN_SERVER}/auth
        - name: auth.image.tag
          value: ${AUTH_TAG}
        - name: ai.image.name
          value: ${ACR_LOGIN_SERVER}/ai
        - name: ai.image.tag
          value: ${AI_TAG}
        - name: hr.image.name
          value: ${ACR_LOGIN_SERVER}/hr
        - name: hr.image.tag
          value: ${HR_TAG}
        - name: finance.image.name
          value: ${ACR_LOGIN_SERVER}/finance
        - name: finance.image.tag
          value: ${FINANCE_TAG}
        - name: projects.image.name
          value: ${ACR_LOGIN_SERVER}/projects
        - name: projects.image.tag
          value: ${PROJECTS_TAG}
        - name: gateway.image.name
          value: ${ACR_LOGIN_SERVER}/gateway
        - name: gateway.image.tag
          value: ${GATEWAY_TAG}
        - name: notification.image.name
          value: ${ACR_LOGIN_SERVER}/notification
        - name: notification.image.tag
          value: ${NOTIFICATION_TAG}
        - name: frontend.enabled
          value: "${FRONTEND_ENABLED}"
        - name: frontend.image.name
          value: ${FRONTEND_IMAGE_NAME}
        - name: frontend.image.tag
          value: ${FRONTEND_TAG}
  destination:
    server: https://kubernetes.default.svc
    namespace: dev-ns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
